//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAndLearn.Domain.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public Test()
        {
            this.TestTypes = new HashSet<TestType>();
            this.TestUrls = new HashSet<TestUrl>();
        }
    
        public int TestId { get; set; }
        public int ClientId { get; set; }
        public System.DateTime SubmittedOn { get; set; }
        public string SubmittedBy { get; set; }
        public string Name { get; set; }
        public string Hypothesis { get; set; }
        public string AdditionalNotes { get; set; }
        public string ExpectedBusinessValue { get; set; }
        public string Quarter { get; set; }
        public Nullable<int> Year { get; set; }
        public int TestStatusId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Outcome { get; set; }
        public string Recommendation { get; set; }
        public Nullable<int> LevelOfEffortToImplement { get; set; }
        public Nullable<int> LevelOfEffortToReportOn { get; set; }
        public Nullable<int> LevelOfBudget { get; set; }
        public Nullable<int> LevelOfImpact { get; set; }
        public Nullable<int> SuccessMetricId { get; set; }
        public Nullable<int> PillarId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual TestStatu TestStatu { get; set; }
        public virtual ICollection<TestType> TestTypes { get; set; }
        public virtual Pillar Pillar { get; set; }
        public virtual SuccessMetric SuccessMetric { get; set; }
        public virtual ICollection<TestUrl> TestUrls { get; set; }
    }
}
