//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAndLearn.Domain.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.UserClientMaps = new HashSet<UserClientMap>();
            this.Tests = new HashSet<Test>();
            this.SuccessMetrics = new HashSet<SuccessMetric>();
            this.TestTypes = new HashSet<TestType>();
            this.Events = new HashSet<Event>();
            this.Pillars = new HashSet<Pillar>();
        }
    
        public int ClientId { get; set; }
        public string ClientName { get; set; }
        public string LogoImageName { get; set; }
    
        public virtual ICollection<UserClientMap> UserClientMaps { get; set; }
        public virtual ICollection<Test> Tests { get; set; }
        public virtual ICollection<SuccessMetric> SuccessMetrics { get; set; }
        public virtual ICollection<TestType> TestTypes { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<Pillar> Pillars { get; set; }
    }
}
